"""remove collections and devices

Revision ID: 2af906dfbeda
Revises: 883180e9f865
Create Date: 2026-07-03 11:45:41.321736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2af906dfbeda'
down_revision: Union[str, None] = '883180e9f865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clipboard_items_collection_id', table_name='clipboard_items')
    op.drop_constraint('clipboard_items_device_id_fkey', 'clipboard_items', type_='foreignkey')
    op.drop_constraint('clipboard_items_collection_id_fkey', 'clipboard_items', type_='foreignkey')
    op.drop_column('clipboard_items', 'device_id')
    op.drop_column('clipboard_items', 'collection_id')
    op.drop_column('refresh_tokens', 'device_id')

    op.drop_index('ix_devices_fingerprint', table_name='devices')
    op.drop_index('ix_devices_user_id', table_name='devices')
    op.drop_table('devices')
    op.execute('DROP TYPE IF EXISTS devicetype')
    op.drop_index('ix_collections_owner_id', table_name='collections')
    op.drop_index('ix_collections_workspace_id', table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('clipboard_items', sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('clipboard_items', sa.Column('device_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('clipboard_items_collection_id_fkey', 'clipboard_items', 'collections', ['collection_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('clipboard_items_device_id_fkey', 'clipboard_items', 'devices', ['device_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_clipboard_items_collection_id', 'clipboard_items', ['collection_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_shared', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='collections_owner_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['collections.id'], name='collections_parent_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='collections_workspace_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='collections_pkey')
    )
    op.create_index('ix_collections_workspace_id', 'collections', ['workspace_id'], unique=False)
    op.create_index('ix_collections_owner_id', 'collections', ['owner_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('device_type', postgresql.ENUM('DESKTOP', 'MOBILE', 'TABLET', 'BROWSER', 'CLI', name='devicetype'), autoincrement=False, nullable=False),
    sa.Column('fingerprint', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('os', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('browser', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_trusted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='devices_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='devices_pkey')
    )
    op.create_index('ix_devices_user_id', 'devices', ['user_id'], unique=False)
    op.create_index('ix_devices_fingerprint', 'devices', ['fingerprint'], unique=True)
    # ### end Alembic commands ###
