"""add meetings table

Revision ID: 4b215236f853
Revises: 2af906dfbeda
Create Date: 2026-07-03 11:49:52.892544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b215236f853'
down_revision: Union[str, None] = '2af906dfbeda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('host_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'ENDED', name='meetingstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_room_code'), 'meetings', ['room_code'], unique=True)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_room_code'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
