"""add shared_secrets table

Revision ID: 883180e9f865
Revises: e52821eb5591
Create Date: 2026-07-03 11:12:20.813675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883180e9f865'
down_revision: Union[str, None] = 'e52821eb5591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_secrets_code'), 'shared_secrets', ['code'], unique=True)
    op.create_index(op.f('ix_shared_secrets_expires_at'), 'shared_secrets', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_secrets_expires_at'), table_name='shared_secrets')
    op.drop_index(op.f('ix_shared_secrets_code'), table_name='shared_secrets')
    op.drop_table('shared_secrets')
    # ### end Alembic commands ###
